from typing import Text, Any


class FlaskClient:
    def __init__(self) -> None: ...
    def get(self, endpoint: str) -> request: ...
    testing: bool


class Flask:
    def __init__(self, import_name: Text) -> None: ...
    route: Any
    def test_client(self) -> FlaskClient: ...


def jsonify(*args, **kwargs) -> Text: ...
def abort(code: int) -> Text: ...
request: Any
